### ISSUE TITLE
Error in help message

### ISSUE THREAD

**Issue by PMunch** [Tomas-M/xlunch#60]
The new `-L, --highlightcolor` is noted as the switch for the new highlight image option, where it should be `-L, --highlight`. This is true for both `--help`, the usage.txt, and the docs.

**Comment by Tomas-M** [comment]
I can see -L is in the help, but I didn't touch the code (-L was not used in the code before I took it).
What to do now? Remove it from the help, or leave it there, implement -L for --highlightcolor, and use another letter for --highlight?

**Comment by Tomas-M** [comment]
We have currently 38 letters used, those are:
abBcdefFgGhHiIlLmMnoOpPqrRsStTuvwWxXy
That means we can still use
ACDEjJkKNQUVYzZ

**Comment by Tomas-M** [comment]
So maybe use -C for highlightcolor?

**Comment by Tomas-M** [comment]
Ah, I misunderstood. I thought there is a --highlightcolor option ...
Now I understand you. Sorry, going to fix. Still, we could use -C for --hc :-)

**Comment by Tomas-M** [comment]
Wait a moment, there is a 'highlightcolor' option.
I should take a break, deep breath, ....  :)

**Comment by Tomas-M** [comment]
Fixed by f60a4f7f7e9ff1f5cd319d23771579b33af38e67, thank you for notice

**Comment by PMunch** [comment]
Haha, glad you figured out what I meant in the end. But it's still wrong in the docs: https://github.com/Tomas-M/xlunch/blob/master/docs/index.html#L109

**Comment by Tomas-M** [comment]
Sorry I've missed that, fixed now f60a4f7f7e9ff1f5cd319d23771579b33af38e67
